
    <div class="row ">

      <!-- home content -->
      <div class="col-md-3"></div>
      <div class="col-md-6">
          <h1 class="text-center">Biblioteca SM</h1>
          <h4 class="text-center">Sistema web para la reserva de Libros
          </h4>
          <div class="text-center">
            <?php echo Html::link('solicitud/pedido', 'Solicitar libro', 'class="btn btn-primary"')  ?>
            <?php echo Html::link('solicitud/devolver', 'Devolución libro', 'class="btn btn-success"') ?>
          </div>
      </div>
      <div class="col-md-3"></div>
      <!-- /home content -->

    </div>
